# Generated by Django 5.2.5 on 2026-02-02 02:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Only text and spaces are allowed.')])),
                ('address', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d+$', message='Only digits are allowed.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentImage', models.ImageField(blank=True, upload_to='')),
                ('contentHeader', models.CharField(max_length=35)),
                ('contentText', models.TextField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptopName', models.CharField(max_length=25)),
                ('laptopImage', models.ImageField(blank=True, upload_to='')),
                ('laptopDetails', models.TextField(max_length=150)),
                ('laptopPrice', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d+\\.?\\d*$', message='Only digits are allowed.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
