# Generated by Django 5.2.5 on 2025-10-06 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Only text and spaces are allowed.')])),
                ('address', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d+$', message='Only digits are allowed.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
