# Generated by Django 5.2.5 on 2026-06-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('location', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
