# Generated by Django 5.2.5 on 2026-02-02 02:06

from django.db import migrations , models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='LaptopsCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('laptopName', models.CharField(max_length=255)),
                ('laptopImage',models.ImageField(blank=True)),
                ('laptopDetails',models.TextField(max_length=150)),
                ('laptopPrice', models.DecimalField(max_digits=10, decimal_places=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                # add any other fields from your LaptopsCard model here
            ],
        ),
    ]
