# Generated by Django 5.2.5 on 2025-10-21 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=25)),
                ('productImage', models.ImageField(blank=True, upload_to='')),
                ('productDetails', models.TextField(max_length=150)),
                ('productPrice', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d+$', message='Only digits are allowed.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
