# Generated by Django 5.2.5 on 2026-02-02 02:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recreate_missing_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopscard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='laptopscard',
            name='laptopName',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='laptopscard',
            name='laptopPrice',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d+\\.?\\d*$', message='Only digits are allowed.')]),
        ),
    ]
