# Generated by Django 5.2.5 on 2025-10-21 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='productPrice',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d+\\.?$', message='Only digits are allowed.')]),
        ),
    ]
