# Generated by Django 5.2.5 on 2026-06-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
