# Generated by Django 5.2.5 on 2025-10-23 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_productcard_productprice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AppUser',
        ),
        migrations.AlterField(
            model_name='productcard',
            name='productPrice',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d+\\.?\\d*$', message='Only digits are allowed.')]),
        ),
    ]
