# Generated by Django 5.2.5 on 2026-06-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_contactpage_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
