# Generated by Django 5.2.5 on 2026-02-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_laptopscard_id_alter_laptopscard_laptopname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopscard',
            name='laptopDetails',
            field=models.TextField(max_length=300),
        ),
    ]
