# Generated by Django 5.2.5 on 2026-01-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_user_appuser_alter_productcard_productprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentImage', models.ImageField(blank=True, upload_to='')),
                ('contentHeader', models.CharField(max_length=35)),
                ('contentText', models.TextField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
