# Generated by Django 5.2.5 on 2026-02-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_laptopscard_laptopdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopscard',
            name='laptopName',
            field=models.CharField(max_length=40),
        ),
    ]
