# Generated by Django 5.2.5 on 2026-08-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_hardwarepage_softwarepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsEmailPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactPage',
        ),
    ]
