# Generated by Django 5.2.5 on 2026-08-30 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contactsemailpage_delete_contactpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactsEmailPage',
        ),
    ]
