# Generated by Django 5.2.5 on 2026-05-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_alter_laptopscard_laptopprice_cart_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LaptopsCard',
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
