# Generated by Django 5.2.5 on 2026-09-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
                ('socket', models.CharField(max_length=9)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
