# Generated by Django 5.2.5 on 2026-09-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_partselector'),
    ]

    operations = [
        migrations.AddField(
            model_name='partselector',
            name='type',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='partselector',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
