# Generated by Django 5.2.5 on 2026-09-11 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_partselector_type_alter_partselector_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Only text and spaces are allowed.')]),
        ),
    ]
