# Generated by Django 5.2.5 on 2026-09-20 19:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_hardwarepage_price_softwarepage_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwarepage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='softwarepage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
    ]
