# Generated by Django 5.2.5 on 2026-09-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_hardwarepage_price_alter_softwarepage_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardwarepage',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='softwarepage',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='hardwarepage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AddField(
            model_name='softwarepage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first'),
        ),
    ]
